name: wastego
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  go_router: ^14.8.1
  http: ^1.3.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.2
  flutter_svg: ^2.0.17
  shimmer: ^3.0.0
  firebase_messaging: ^15.2.4
  firebase_core: ^3.12.1
  intl: ^0.19.0
  lucide_icons: ^0.257.0
  image_picker: any
  url_launcher: ^6.3.1
  percent_indicator: ^4.2.2
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.1
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.14.3
  fluttertoast: ^8.2.12
  flutter_localization: ^0.3.2
  share_plus: ^11.0.0
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/banner.svg
    - assets/images/logo.png
    - assets/images/logo.svg
    - assets/images/profile.png
    - assets/images/logotext.png
    - assets/images/
    - assets/icons/
    - assets/images/reuse.svg
    - assets/images/reduce.svg
    - assets/images/recycle.svg
    - assets/animation/success.json

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  android_icon_size: 100

